apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: {{ .Release.Namespace }}
  labels:
    app: telegraf
{{ include "common.labels" . | indent 4 }}
spec:
  serviceName: telegraf
  # replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      name: telegraf
      labels:
        app: telegraf
    spec:
      containers:
        - image: {{ .Values.telegraf.image }}
          name: telegraf
          ports:
            - containerPort: 8125
          resources: {}
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-conf
              subPath: telegraf.conf
      restartPolicy: Always
      volumes:
      - name: telegraf-conf
        configMap:
          name: telegraf-conf
          items:
          - key: telegraf.conf
            path: telegraf.conf