apiVersion: v1
kind: Service
metadata:
  name: telegraf
  namespace: {{ .Release.Namespace }}
  labels:
    app: telegraf
{{ include "common.labels" . | indent 4 }}
spec:
  ports:
    - name: telegraf
      port: 8125
      targetPort: 8125
  selector:
    app: telegraf
  clusterIP: None
