apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homer-webapp
{{ include "common.labels" . | indent 4 }}
  name: homer-webapp
  namespace: {{ dig "global" "monitoring" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer-webapp
  template:
    metadata:
      labels:
        app: homer-webapp
      annotations:
        checksum/secret: {{ (fromYaml (include (print $.Template.BasePath "/homer-webapp/secret.yaml") . )).data | toString | sha256sum }}
        checksum/secret-config: {{ (fromYaml (include (print $.Template.BasePath "/homer-webapp/secret-config.yaml") . )).data | toString | sha256sum }}
    spec:
      containers:
        - name: homer-webapp
          image: {{ .Values.homer.image }}
          ports:
            - containerPort: 80
          resources: {}
          env:
            - name: DB_HOST
              value: {{ .Values.postgresql.host }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: homer-webapp
                  key: dbUsername
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: homer-webapp
                  key: dbPassword
          volumeMounts:
            - mountPath: /usr/local/homer/etc/webapp_config.json
              name: homer-webapp-config
              subPath: webapp_config.json
            - mountPath: /homer-semaphore/.bootstrapped
              name: homer-webapp-config
              subPath: bootstrapped
      volumes:
        - name: homer-webapp-config
          secret:
            defaultMode: 0400
            secretName: homer-webapp-config