---
apiVersion: v1
kind: Secret
metadata:
  name: homer-webapp
  namespace: {{ .Release.Namespace }}
  labels:
    app: homer-webapp
    {{- include "common.labels" . | nindent 4 }}
data:
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "homer-webapp") }}
{{- if $secret }}
  adminUser: {{ index $secret.data "adminUser" | default (.Values.homer.admin.username | b64enc) }}
  adminPassword: {{ index $secret.data "adminPassword" | default (.Values.homer.admin.password | default (randAlphaNum 20) | b64enc) }}
  dbUsername: {{ index $secret.data "dbUsername" | default (.Values.homer.db.username | b64enc) }}
  dbPassword: {{ index $secret.data "dbPassword" | default (.Values.homer.db.password | default (randAlphaNum 20) | b64enc) }}
{{- else }}
  adminUser: {{ .Values.homer.admin.username | b64enc }}
  adminPassword: {{ .Values.homer.admin.password | default (randAlphaNum 20) | b64enc }}
  dbUsername: {{ .Values.homer.db.username | b64enc }}
  dbPassword: {{ .Values.homer.db.password | default (randAlphaNum 20) | b64enc }}
{{- end }}
