apiVersion: v1
kind: Service
metadata:
  name: homer-webapp
  namespace: {{ .Release.Namespace }}
  labels:
    app: homer-webapp
{{ include "common.labels" . | indent 4 }}
spec:
  ports:
    - name: homer-webapp
      port: 80
      targetPort: 80
  type: NodePort
  selector:
    app: homer-webapp
