apiVersion: v1
kind: Service
metadata:
  name: homer-webapp
  namespace: {{ .Release.Namespace }}
  labels:
    app: homer-webapp
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9080
      name: http
      targetPort: http
    - port: 9443
      name: https
      targetPort: https
  selector:
    app: homer-webapp
    {{- include "common.labels" . | nindent 4 }}
