apiVersion: v2
name: sipcapture
version: 1.0.0
appVersion: 0.0.1
description: HOMER/SIPCAPTURE stack
home: https://sipcapture.org
icon: https://user-images.githubusercontent.com/1423657/55069501-8348c400-5084-11e9-9931-fefe0f9874a7.png
keywords:
  - voip 
  - monitoring 
  - pcap 
  - sip 
  - rtp
maintainers: 
  - name: Dave Horton
    email: daveh@drachtio.org
  - name: Lorenzo Mangani
    email: lorenzo.mangani@gmail.com
  - name: Michael Kanchuker
    email: michaelkanchuker@gmail.com
sources: 
  - https://github.com/sipcapture/helm-charts
  - https://github.com/jambonz/helm-charts
dependencies:
  - name: postgresql
    version: 16.2.1
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: postgresql.installOnCluster