grafana: 
  installOnCluster: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/use-regex: "true"
    path: /grafana/?(.*)
    hosts:
      - grafana.domain.com
  grafana.ini:
    server:
      root_url: http://localhost:3000/grafana # this host can be localhost
    log.console:
      level: info

  adminUser: admin
  adminPassword: "admin"

  sidecar:
    datasources:
      enabled: true
    dashboards:
      enabled: true

  persistence:
    enabled: true
    size: 2Gi

heplifyServer: 
  image: ghcr.io/sipcapture/heplify-server:latest
influxdb: 
  image: influxdb:1.8
  loglevel: info
  storage: 10Gi
homer: 
  image: ghcr.io/sipcapture/homer-app:latest
  hostname:
postgres: 
  image: postgres:11-alpine
  storage: 30Gi 
telegraf: 
  image: telegraf:1.19

