grafana: 
  image: grafana/grafana-oss:latest 
  hostname:
  storage: 2Gi
heplifyServer: 
  image: ghcr.io/sipcapture/heplify-server:latest
influxdb: 
  image: influxdb:1.8
  loglevel: info
  storage: 10Gi
homer: 
  image: ghcr.io/sipcapture/homer-app:latest
  hostname:
postgres: 
  image: postgres:11-alpine
  storage: 30Gi 
telegraf: 
  image: telegraf:1.19

