apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_datasource: 'true' # default value for: sidecar.datasources.label
data:
  datasources.yaml: |
{{ (tpl (.Files.Get "configs/grafana/datasources.yaml") . ) | indent 4}}
