apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: {{ .Release.Namespace }}
  labels:
    app: influxdb
{{ include "common.labels" . | indent 4 }}
spec:
  ports:
    - name: "influxdb"
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb
  clusterIP: None
