apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
{{ include "common.labels" . | indent 4 }}
  name: grafana
  namespace: {{ dig "global" "monitoring" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
spec:
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
  type: NodePort
  selector:
    app: grafana
