apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
{{ include "common.labels" . | indent 4 }}
  name: influxdb
  namespace: {{ dig "global" "monitoring" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
spec:
  ports:
    - name: "influxdb"
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb
  clusterIP: None
