apiVersion: v1
kind: Service
metadata:
  labels:
    app: telegraf
{{ include "common.labels" . | indent 4 }}
  name: telegraf
  namespace: {{ dig "global" "monitoring" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
spec:
  ports:
    - name: telegraf
      port: 8125
      targetPort: 8125
  selector:
    app: telegraf
  clusterIP: None
