apiVersion: v1
kind: Secret
metadata:
  name: postgres-homer-credentials
type: Opaque
data: {{- (include "gen.postgres.secret" . ) | nindent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: homer-ui-credentials
type: Opaque
data: {{- (include "gen.defaultpassword.secret" . ) | nindent 2 }}