apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ include "telegraf.fullname" . }}
{{ include "common.labels" . | indent 4 }}
  name: {{ include "telegraf.fullname" . }}
  namespace: {{ dig "global" "monitoring" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
spec:
  serviceName: {{ include "telegraf.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "telegraf.fullname" . }}
  template:
    metadata:
      name: {{ include "telegraf.fullname" . }}
      labels:
        app: {{ include "telegraf.fullname" . }}
    spec:
      {{- include "telegraf.imagePullSecrets" . | nindent 6 }}
      containers:
        - image: "{{ .Values.telegraf.image.registry }}/{{ .Values.telegraf.image.repository }}:{{ .Values.telegraf.image.tag }}"
          imagePullPolicy: {{ .Values.telegraf.image.pullPolicy }}
          name: telegraf
          ports:
            - containerPort: 8125
          resources: {}
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-conf
              subPath: telegraf.conf
      restartPolicy: Always
      volumes:
      - name: telegraf-conf
        configMap:
          name: telegraf-conf
          items:
          - key: telegraf.conf
            path: telegraf.conf
