apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "homer.fullname" . }}
{{ include "common.labels" . | indent 4 }}
  name: {{ include "homer.fullname" . }}
  namespace: {{ dig "global" "monitoring" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "homer.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "homer.fullname" . }}
    spec:
      {{- include "homer.imagePullSecrets" . | nindent 6 }}
      initContainers:
      - name: copy-config
        image: "{{ .Values.homer.image.registry }}/{{ .Values.homer.image.repository }}:{{ .Values.homer.image.tag }}"
        imagePullPolicy: {{ .Values.homer.image.pullPolicy }}
        command:
          - sh
          - -c
          - |
            set -e -o pipefail
            cp /webapp_config.json /config
            cp /usr/local/homer/etc/swagger.json /config
        volumeMounts:
          - mountPath: /webapp_config.json
            name: webapp-conf
            subPath: webapp_config.json
          - mountPath: /config
            name: config-dir
      - name: init-db
        image: "{{ .Values.homer.image.registry }}/{{ .Values.homer.image.repository }}:{{ .Values.homer.image.tag }}"
        imagePullPolicy: {{ .Values.homer.image.pullPolicy }}
        env:
          - name: DB_HOST
            value: "{{ .Values.postgresql.hostname }}"
          - name: DB_PORT
            value: "{{ default "5432" .Values.postgresql.port }}"
          - name: DB_ROOT_USER
            {{- if .Values.postgresql.auth.existingSecret }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresql.auth.existingSecret }}
                key: postgres-user
            {{- else }}
            value: "{{ .Values.postgresql.auth.postgresUser }}"
            {{- end }}
          - name: DB_ROOT_PASSWORD
            {{- if .Values.postgresql.auth.existingSecret }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresql.auth.existingSecret }}
                key: postgres-password
            {{- else }}
            value: "{{ .Values.postgresql.auth.postgresPassword }}"
            {{- end }}
          - name: DB_HOMER_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresql.auth.existingSecretHomer }}
                key: postgres-user
          - name: DB_HOMER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresql.auth.existingSecretHomer }}
                key: postgres-password
        command:
          - sh
          - -c
          - |
            set -e -o pipefail
            echo [*] "Creating homer user"
            /homer-app -create-homer-user \
                       -database-host=$DB_HOST \
                       -database-port=$DB_PORT \
                       {{- if eq .Values.postgresql.sslmode "enable" }}
                       -database-ssl-mode=enable \
                       {{- end }}
                       -database-homer-password=$DB_HOMER_PASSWORD \
                       -database-root-user=$DB_ROOT_USER \
                       -database-root-password=$DB_ROOT_PASSWORD
            echo [*] Creating config DB
            /homer-app -create-config-db \
                       -database-host=$DB_HOST \
                       -database-port=$DB_PORT \
                       {{- if eq .Values.postgresql.sslmode "enable" }}
                       -database-ssl-mode=enable \
                       {{- end }}
                       -database-homer-user=$DB_HOMER_USER \
                       -database-homer-password=$DB_HOMER_PASSWORD \
                       -database-root-user=$DB_ROOT_USER \
                       -database-root-password=$DB_ROOT_PASSWORD \
                       -webapp-config-path=/usr/local/homer/etc
            echo [*] Creating data DB
            /homer-app -create-data-db \
                       -database-host=$DB_HOST \
                       -database-port=$DB_PORT \
                       -database-homer-user=$DB_HOMER_USER \
                       -database-homer-password=$DB_HOMER_PASSWORD \
                       -database-root-user=$DB_ROOT_USER \
                       -database-root-password=$DB_ROOT_PASSWORD \
                       {{- if eq .Values.postgresql.sslmode "enable" }}
                       -database-ssl-mode=enable \
                       {{- end }}
                       -webapp-config-path=/usr/local/homer/etc
            echo [*] Creating homer role
            /homer-app -create-homer-role \
                       -database-host=$DB_HOST \
                       -database-port=$DB_PORT \
                       {{- if eq .Values.postgresql.sslmode "enable" }}
                       -database-ssl-mode=enable \
                       {{- end }}
                       -database-root-user=$DB_ROOT_USER \
                       -database-root-password=$DB_ROOT_PASSWORD
        volumeMounts:
          - mountPath: /usr/local/homer/etc
            name: config-dir

      containers:
        - name: homer-webapp
          image: "{{ .Values.homer.image.registry }}/{{ .Values.homer.image.repository }}:{{ .Values.homer.image.tag }}"
          imagePullPolicy: {{ .Values.homer.image.pullPolicy }}
          ports:
            - containerPort: 80
          args:
            - /homer-app
            {{- if eq .Values.postgresql.sslmode "enable" }}
            - -database-ssl-mode=enable
            {{- end }}
            - -webapp-config-path=/usr/local/homer/etc
          resources: {}
          env:
            - name: DB_HOST
              value: "{{ .Values.postgresql.hostname }}"
            - name: DB_ROOT_USER
              {{- if .Values.postgresql.auth.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.auth.existingSecret }}
                  key: postgres-user
              {{- else }}
              value: "{{ .Values.postgresql.auth.postgresUser }}"
              {{- end }}
            - name: DB_ROOT_PASS
              {{- if .Values.postgresql.auth.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.auth.existingSecret }}
                  key: postgres-password
              {{- else }}
              value: "{{ .Values.postgresql.auth.postgresPassword }}"
              {{- end }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.auth.existingSecretHomer }}
                  key: postgres-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.auth.existingSecretHomer }}
                  key: postgres-password
            - name: PROVISIONED_USERS_PASS
              valueFrom:
                secretKeyRef:
                  name: homer-ui-credentials
                  key: default-password
          volumeMounts:
            - mountPath: /usr/local/homer/etc
              name: config-dir
            - mountPath: /homer-semaphore/.bootstrapped
              name: webapp-conf
              subPath: bootstrapped
      volumes:
      - name: webapp-conf
        configMap:
          name: webapp-conf
          items:
          - key: webapp_config.json
            path: webapp_config.json
          - key: bootstrapped
            path: bootstrapped
      - name: config-dir
        emptyDir: {}
