apiVersion: apps/v1
kind: Deployment
metadata:
  name: heplify-server
  labels:
    app: heplify-server
{{ include "common.labels" . | indent 4 }}
  namespace: {{ dig "global" "monitoring" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heplify-server
  template:
    metadata:
      labels:
        app: heplify-server
      annotations:
        checksum/secret: {{ (fromYaml (include (print $.Template.BasePath "/heplify-server/secret.yaml") . )).data | toString | sha256sum }}
        checksum/secret-config: {{ (fromYaml (include (print $.Template.BasePath "/heplify-server/secret-config.yaml") . )).data | toString | sha256sum }}
    spec:
      containers:
        - name: heplify-server
          image: {{ .Values.heplifyServer.image }}
          args: ['./heplify-server', '-config', '/etc/heplify-server.toml']
          ports:
            - containerPort: 9060
              protocol: UDP
            - containerPort: 9096
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/heplify-server.toml
              name: heplify-server-config
              subPath: heplify-server.toml
      volumes:
        - name: heplify-server-config
          secret:
            defaultMode: 0400
            secretName: heplify-server-config
