---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: heplify-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: heplify-server
    {{- include "common.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: heplify-server
      {{- include "common.labels" . | nindent 6 }}
