apiVersion: v1
kind: Secret
metadata:
  name: heplify-server-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: heplify-server
    {{- include "common.labels" . | nindent 4 }}
data:
  heplify-server.toml: {{ tpl (toString .Values.heplifyServer.config) . | b64enc }}