---
apiVersion: v1
kind: Secret
metadata:
  name: heplify-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: heplify-server
    {{- include "common.labels" . | nindent 4 }}
data:
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "heplify-server") }}
{{- if $secret }}
  dbUsername: {{ index $secret.data "dbUsername" | default (.Values.heplifyServer.db.username | b64enc) }}
  dbPassword: {{ index $secret.data "dbPassword" | default (.Values.heplifyServer.db.password | default (randAlphaNum 20) | b64enc) }}
{{- else }}
  dbUsername: {{ .Values.heplifyServer.db.username | b64enc }}
  dbPassword: {{ .Values.heplifyServer.db.password | default (randAlphaNum 20) | b64enc }}
{{- end }}
