apiVersion: v1
kind: Service
metadata:
  name: heplify-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: heplify-server
{{ include "common.labels" . | indent 4 }}
spec:
  ports:
    - name: "heplify-server"
      port: 9060
      targetPort: 9060
      protocol: UDP
    - name: "stats-scraper"
      port: 9096
      targetPort: 9096
      protocol: TCP
  selector:
    app: heplify-server
  clusterIP: None
